version: '3.3'

services:

    build-beyond0lte:
        build: ./docker-lineage-cicd
        volumes:
            - ./volumes/lineage:/srv/src
            - ./volumes/zips:/srv/zips
            - ./volumes/logs:/srv/logs
            - ./volumes/cache:/srv/ccache
            - ./volumes/keys:/srv/keys
            - ./volumes/manifests/beyond0lte:/srv/local_manifests
            - ./volumes/patches/beyond0lte:/srv/patches
            - ./volumes/userscripts/beyond0lte:/srv/userscripts
        env_file:
            - .env
        environment:
            BRANCH_NAME: lineage-19.1
            DEVICE_LIST: beyond0lte
            SIGN_BUILDS: 'true'
            SIGNATURE_SPOOFING: restricted
            WITH_GMS: 'true'
            INCLUDE_PROPRIETARY: 'true'
            CUSTOM_PACKAGES: "GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension"
            CLEAN_OUTDIR: 'false'
            DELETE_OLD_ZIPS: 0
            DELETE_OLD_LOGS: 0
            CLEAN_AFTER_BUILD: 'false'
            ZIP_SUBDIR: 'false'
            REPO_SYNC: 'true'
            OTA_URL: "https://${DOMAIN_NAME}/api"

    build-herolte:
        stdin_open: true
        tty: true
        build: ./docker-lineage-cicd
        volumes:
            - ./volumes/lineage:/srv/src
            - ./volumes/zips:/srv/zips
            - ./volumes/logs:/srv/logs
            - ./volumes/cache:/srv/ccache
            - ./volumes/keys:/srv/keys
            - ./volumes/manifests/herolte:/srv/local_manifests
            - ./volumes/patches/herolte:/srv/patches
            - ./volumes/userscripts/herolte:/srv/userscripts
        env_file:
            - .env
        environment:
            BRANCH_NAME: lineage-19.1
            DEVICE_LIST: herolte
            SIGN_BUILDS: 'true'
            SIGNATURE_SPOOFING: restricted
            WITH_GMS: 'true'
            INCLUDE_PROPRIETARY: 'false'
            CUSTOM_PACKAGES: "GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension"
            CLEAN_OUTDIR: 'false'
            DELETE_OLD_ZIPS: 0
            DELETE_OLD_LOGS: 0
            CLEAN_AFTER_BUILD: 'false'
            ZIP_SUBDIR: 'false'
            REPO_SYNC: 'true'
            OTA_URL: "https://${DOMAIN_NAME}/api"

    build-a51:
        build: ./docker-lineage-cicd
        volumes:
            - ./volumes/lineage:/srv/src
            - ./volumes/zips:/srv/zips
            - ./volumes/logs:/srv/logs
            - ./volumes/cache:/srv/ccache
            - ./volumes/keys:/srv/keys
            - ./volumes/manifests/a51:/srv/local_manifests
            - ./volumes/patches/a51:/srv/patches
            - ./volumes/userscripts/a51:/srv/userscripts
        env_file:
            - .env
        environment:
            BRANCH_NAME: lineage-20
            DEVICE_LIST: a51
            SIGN_BUILDS: 'true'
            SIGNATURE_SPOOFING: restricted
            WITH_GMS: 'true'
            INCLUDE_PROPRIETARY: 'false'
            CUSTOM_PACKAGES: "GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension"
            CLEAN_OUTDIR: 'false'
            DELETE_OLD_ZIPS: 0
            DELETE_OLD_LOGS: 0
            CLEAN_AFTER_BUILD: 'false'
            ZIP_SUBDIR: 'false'
            REPO_SYNC: 'true'

    ota-server:
        env_file:
            - .env
        build: 
            context: ./docker-lineage-ota
            dockerfile: Dockerfile
            args:
              DOMAIN_NAME: ${DOMAIN_NAME}
        restart: always
        volumes:
            - ./volumes/zips:/var/www/html/builds/full:ro
            - ../lamp/fs/etc/letsencrypt:/etc/letsencrypt
        ports:
            - 4000:80
            - 4443:443
        networks:
          - ota

    monitor:
        build: ./docker-lineage-monitor
        restart: always
        volumes:
            - ./volumes/logs:/root/logs:ro
            - ./volumes/zips:/root/zips:ro
        ports:
            - 3050:3000
networks:
  ota:
    name: ota
    external: true
